CREATE DATABASE IF NOT EXISTS loja_motors_test;

USE loja_motors;

DROP TABLE IF EXISTS veiculos;
DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS montadoras;

CREATE TABLE IF NOT EXISTS montadoras(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(60) NOT NULL,
    Pais VARCHAR(45) NOT NULL,
    DataCad TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    Logradouro VARCHAR(255) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    Numero VARCHAR(20) NOT NULL,
    Complemento VARCHAR(100) NULL,
    DataCad TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS veiculos(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    IdMontadora INT NOT NULL,
    IdCliente INT NOT NULL,
    Modelo VARCHAR(60) NOT NULL,
    Placa VARCHAR(10) NOT NULL,
    Ano INT NOT NULL,
    Cor VARCHAR(30) NOT NULL,
    Valor DECIMAL(10,2) NOT NULL,
    DataCad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_veiculos_montadoras
        FOREIGN KEY (IdMontadora)
        REFERENCES montadoras(Id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_veiculos_clientes
        FOREIGN KEY (IdCliente)
        REFERENCES clientes(Id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

